#!/bin/bash

cd application
php bin/composer install -o --no-scripts --no-suggest
php bin/composer init-example
php bin/console assets:install --symlink --relative
php bin/console mapbender:database:init -v
php bin/console lexik:jwt:generate-keypair
sed -i "s/^JWT_PASSPHRASE=<change_me>/JWT_PASSPHRASE=$(openssl rand -base64 32)/" application/.env
php bin/composer run post-install-cmd
echo Bootstrap finished!
echo If you want to run the builtin development server, install Symfony CLI from https://symfony.com/download then run:
echo ' cd application'
echo ' symfony server:start --no-tls'
