<?php

# The actual body of this file is re-generated by sensio/distribution-bundle after every
# composer install or composer update
# If you're missing the functional parts of this file, please simply run
# bin/composer install
# This will NOT change any installed packages
