security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        main:
            entity:
                class: FOM\UserBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|components)/
            security: false
        login:
            pattern:  ^/user/login$
            security: false

        jwt_login:
          pattern: ^/api/login_check
          stateless: true
          json_login:
            provider: main
            check_path: /api/login_check # or api_login_check as defined in config/routes.yaml
            success_handler: lexik_jwt_authentication.handler.authentication_success
            failure_handler: mapbender.api.handler.authentication_failure

        api:
          provider: main
          pattern: ^/api(?!/doc$)
          stateless: true
          jwt: ~

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /user/login/check
                login_path: /user/login
                enable_csrf: true
            logout:
                path:   /user/logout
                target: /

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/user/login,    roles: PUBLIC_ACCESS }
        - { path: ^/manager,       roles: ROLE_USER }
        - { path: ^/api/login_check,     roles: PUBLIC_ACCESS }
        - { path: ^/api/doc,       roles: PUBLIC_ACCESS }
        - { path: ^/api,           roles: IS_AUTHENTICATED_FULLY }
    password_hashers:
        FOM\UserBundle\Entity\User: sha512

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
