parameters:
    applications:
        mapbender_mobile:
            title: Mapbender Mobile Demo
            screenshot: screenshot.png
            description: Mapbender application using mobile template
            published: true
            template:  'Mapbender\MobileBundle\Template\Mobile'
            custom_css: null
            layersets:
                themes:
                    selected: true
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml
                        version: 1.3.0
                        layers:
                            4: { name: Mapbender_User,    title : User, visible: true, legendurl: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mapbender_User&format=image/png&STYLE=default }
                            5: { name: Mapbender_Names,   title : Name, visible: true, queryable: true}
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 100
                        isBaseSource: false
                        toggle: true
                    fossgis:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: FOSSGIS Konferenzen
                        url: https://wms.wheregroup.com/cgi-bin/fossgis.xml
                        version: 1.3.0
                        layers:
                            6: { name: FOSSGIS, title : FOSSGIS Konferenz-Standorte, visible: true, queryable: true, legendurl: https://wms.wheregroup.com/cgi-bin/fossgis.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=fossgis&format=image/png&STYLE=default }
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 100
                        isBaseSource: false
                        toggle: false
                    foss4g:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: FOSS4G Conferences
                        url: https://wms.wheregroup.com/cgi-bin/foss4g.xml
                        version: 1.3.0
                        layers:
                            6: { name: FOSS4G, title : FOSS4G Conference Locations, visible: true, queryable: true, legendurl: https://wms.wheregroup.com/cgi-bin/foss4g.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=foss4g&format=image/png&STYLE=default }
                        info_format: text/html
                        visible: false
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 100
                        isBaseSource: false
                        toggle: false
                background themes:
                    selected: true
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            12: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 100
                        isBaseSource: true
                    osm-transparent:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            12: { name: osm,    title : OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: false
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 60
                        isBaseSource: true
                    osm-greyscale:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            13: { name:  osm-grey,    title : OSM Demo WhereGroup (greyscale),  visible: true }
                        info_format: text/html
                        visible: false
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 100
                        isBaseSource: true
            elements:
                footer:
                    # button parameters: action,activate,deactivate are ignored for elements at mobilePane
                    layertree-button:
                        title: mb.demoapps.themes
                        tooltip: Themes
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: icon-layer-tree
                        target: layertree

                    bss-button:
                        class: Mapbender\CoreBundle\Element\ControlButton
                        icon: iconMap
                        label: false
                        target: basesourceswitcher

                    gps-button:
                        class: Mapbender\CoreBundle\Element\GpsPosition
                        label: false
                        target: map
                        icon: iconGps
                        average: '1'
                        follow: false
                        centerOnFirstPosition: true
                        zoomToAccuracyOnFirstPosition: true

                    legend-button:
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconLegend
                        target: legend

                    routing-button:
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconRouting
                        target: routing

                    imprint-button:
                        title: Imprint
                        tooltip: Imprint
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconInfoActive
                        target: imprint
                        screenType: desktop

                    help-button:
                        title: mb.core.aboutdialog.tag.help
                        tooltip: mb.core.aboutdialog.tag.help
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconHelp
                        target: help
                        screenType: desktop

                    about-mapbender-button:
                        title: mb.core.aboutdialog.tag.about
                        tooltip: mb.core.aboutdialog.tag.about
                        class: Mapbender\CoreBundle\Element\ControlButton
                        label: false
                        icon: iconAbout
                        target: html-about-mapbender

                    shareUrl:
                        class: Mapbender\CoreBundle\Element\ShareUrl
                        label: false
                content:
                    map:
                        class: Mapbender\CoreBundle\Element\Map
                        layersets: [themes,background themes]
                        srs: EPSG:3857
                        extents:
                            start: [772933.16,6566826.23,806786.66,6582317.62]
                            max: [-20037508.34278924,-20037508.34278924,20037508.34278924,20037508.34278924]
                        scales: [50000000,25000000,10000000,5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                        otherSrs: ["EPSG:25832","EPSG:25833","EPSG:31466","EPSG:31467","EPSG:4326"]

                    simplesearch:
                        title: mb.core.simplesearch.class.title
                        placeholder: mb.demoapps.search
                        class: Mapbender\CoreBundle\Element\SimpleSearch
                        target: map
                        anchor: right-top
                        query_url: https://osm-photon-search.wheregroup.com/search/api?limit=20&lat=50.7163&lon=7.1366&osm_tag=!railway&osm_tag=!highway:elevator&osm_tag=!tourism&osm_tag=!amenity
                        query_key: q
                        query_format: '%s'
                        token_regex: '[^a-zA-Z0-9äöüÄÖÜß]'
                        token_regex_in: '([a-zA-ZäöüÄÖÜß]{3,})'
                        token_regex_out: '$1*'
                        collection_path: features
                        label_attribute:  '${properties.name} ${properties.street} ${properties.housenumber} ${properties.city} ${properties.country}'
                        geom_attribute: geometry
                        sourceSrs: 'EPSG:4326'
                        geom_format: GeoJSON
                        delay: 300
                        query_ws_replace: null
                        result:
                            buffer: ~
                            minscale: 500
                            maxscale: 5000
                            icon_url: '/bundles/mapbendercore/image/pin_red.png'
                            icon_offset: '-6,-32'

                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        components: ["zoom_in_out", "zoom_max","zoom_home"]
                        anchor: right-bottom
                        draggable: false

                mobilePane:
                    layertree:
                        title: mb.demoapps.themes
                        class: Mapbender\CoreBundle\Element\Layertree
                        target: map
                        type: element
                        autoOpen: false
                        showBaseSource: false
                        menu: []

                    featureinfo:
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        target: map
                        deactivateOnClose: false
                        autoActivate: true
                        printResult: false
                        displayType: tabs
                        onlyValid: true

                    legend:
                        class: Mapbender\CoreBundle\Element\Legend
                        target: map
                        elementType: dialog
                        autoOpen: false
                        showLayerTitle: true
                        showGroupedLayerTitle: true

                    imprint:
                        title: Imprint
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: "<div style=\"color:#009ee0; font-weight:normal\" >powered by Mapbender.
                        Read more about Mapbender at the <a href=\"https://www.mapbender.org\" target=\"_blank\">Mapbender Project Page</a>.
                        </div>
                        <a href=\"https://mapbender.org\" target=\"_blank\">
                          <p>
                            <img src=\"../image/Mapbender-logo.png\" alt=\"Mapbender\"  title=\"Mapbender\" width=\"200\">
                          </p>
                          <p>https://mapbender.org</p>
                        </a>"
                        classes: html-element-inline
                        screenType: desktop

                    help:
                        title: mb.core.aboutdialog.tag.help
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: "<p>Enjoy the Mapbender mobile Template.
                        Please note that not all elements can be used in the mobile application.</p>
                        <p>Please check the documentation</p>
                        <a href=\"https://doc.mapbender.org\" target=\"_blank\">
                          <p>
                            <img src=\"../image/Mapbender-logo.png\" alt=\"Mapbender\"  title=\"Mapbender\" width=\"200\">
                          </p>
                          <p>https://doc.mapbender.org</p>
                        </a>"
                        classes: html-element-inline
                        screenType: desktop

                    basesourceswitcher:
                        title: mb.core.basesourceswitcher.class.title
                        tooltip: mb.core.basesourceswitcher.class.title
                        class: Mapbender\CoreBundle\Element\BaseSourceSwitcher
                        target: map
                        instancesets:
                            1-basesourceswitcher:
                                title: OSM (color)
                                group: null
                                instances:
                                    - osm
                            2-basesourceswitcher:
                                title: OSM (greyscale)
                                group: null
                                instances:
                                    - osm-greyscale
                            3-basesourceswitcher:
                                title: OSM (transparent)
                                group: null
                                instances:
                                    - osm-transparent
                            4-basesourceswitcher:
                                title: mb.demoapps.noBackground
                                group: null
                                instances: []

                    html-about-mapbender:
                        title: mb.core.aboutdialog.tag.about
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        classes: html-element-inline
                        content: "<p>Learn more about Mapbender</p>
                           <a href=\"https://mapbender.org\" target=\"_blank\">
                             <p>
                             	<img src=\"../image/Mapbender-logo.png\" alt=\"Mapbender\"  title=\"Mapbender\" width=\"200\"><br>https://mapbender.org
                             </p>
                           </a>
                           <ul>
                           	<li>&#8594; add <a href=\"#\" data-mb-action=\"source.add.wms\" data-mb-layer-merge=\"0\" data-mb-wms-merge=\"0\" data-mb-url=\"https://wms.wheregroup.com/cgi-bin/mapbender_user.xml?VERSION=1.3.0&amp;REQUEST=GetCapabilities&amp;SERVICE=WMS\" data-mb-infoformat=\"text/html\">WMS Mapbender Users</a></li>
                           </ul>
                           <p></p>
                           <p>Mapbender is an</p>
                           <a href=\"https://www.osgeo.org/projects/mapbender/\" target=\"_blank\">
                             <p>
                               <img src=\"../bundles/mapbendercore/image/OSGeo_project.png\" alt=\"OSGeo Project\"  title=\"OSGeo Project\" width=\"150\">
                             </p>
                           </a>
                           <p>
                             <a href=\"https://www.osgeo.org\" target=\"_blank\">https://www.osgeo.org</a>
                           </p>"
